### ISSUE TITLE
VSIX will not install into Visual Studio Community 2019 (Version 16.4.5)

### ISSUE THREAD

**Issue by Protiguous** [RedOrc/ProjectHero2#8]
https://marketplace.visualstudio.com/items?itemName=RedOrc.ProjectHero2 lists **VS2019** as an available install option, yet the package will not install.

**Comment by michaelm7456** [comment]
Hi Protiguous,

I've added a Pull Request with some changes to the VSIX Manifest file to allow support for Visual Studio 2019, in case this is of interest.

#8 - [Update VSIX Manifest file to allow Extension to run in Visual Studio 2019](https://github.com/RedOrc/ProjectHero2/pull/9)

Hope this helps!
